### ISSUE TITLE
constant unexplained lightning after playing for a bit

### ISSUE THREAD

**Issue by ArchivesOfFae** [DaoOfModding/Cultivationcraft#4]
I have no idea why this is happening but whenever I have a world open for more than a few minutes there will be lightning flashes and thunder sounds from some unclear location escalating in frequency over time without stopping for no clear reason. The only mod I have installed other than this and its dependency is JEI, so it pretty much has to be this causing it.

**Comment by DaoOfModding** [comment]
It definitely _is_ this causing it.

It sounds like you're near a lightning Qi Source - they are extremely rare, so it's very unlikely for them to spawn, but one of their side-effects is constant lightning strikes in the area of the Qi Source. If you activate Qi Sight it will be up in the sky somewhere and have Yellow Qi particles.

Next update (_Almost_ here, in the middle of a move atm so that's slowing me down a lot >>) will have a config option to disable elemental effects of Qi Sources (Ice freezing everything in range, Fire setting everything in range on fire, Lightning calling down constant lightning strikes, etc), but for the moment if it's too annoying the only two solutions would be to either move away from the lightning source or to create a new world. It's a 1/50 chance for a Wind Qi Source to mutate into a Lightning one, so they're very rare and highly unlikely to spawn.

**Comment by ArchivesOfFae** [comment]
Thanks for the clarification and good luck with the update

**Comment by DaoOfModding** [comment]
Options added with last update
